# â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€Commonly Used ImplementationGuide Propertiesâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
# â”‚  The properties below are used to create the ImplementationGuide resource. The most commonly   â”‚
# â”‚  used properties are included. For a list of all supported properties and their functions,     â”‚
# â”‚  see: https://fshschool.org/docs/sushi/configuration/.                                         â”‚
# â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
id: hl7.fhir.hmis
canonical: https://fhir.hmis.gov.np
name: NPCoreImplementationGuide
title: Nepal HMIS FHIR Implementation Guide â€“ ðŸš¨ DRAFT VERSION
description: >-
  The Electronic Health Management Information System (E-HMIS) FHIR Implementation Guide defines the core profiles, data elements, workflows, and terminologies necessary to support interoperable, standards-based reporting and service delivery for Nepalâ€™s routine health information systems.

  This guide aligns with national data standards, WHO Digital Adaptation Kits (DAKs), and global FHIR best practices. It enables structured data exchange between digital health systems and the national DHIS2-based HMIS platform, improving the accuracy, timeliness, and use of health data for decision-making.

  It is developed to support routine service delivery programs such as Maternal and Child Health, CB-IMNCI, Immunization, and Basic Health Services, and will evolve to integrate real-time analytics, feedback loops, and decentralized data entry mechanisms.
status: active
version: 0.0.1-ballot
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
license: CC-BY-SA-3.0
jurisdiction: urn:iso:std:iso:3166#NP
publisher:
  name: Integrated Health Information Management Section
  url: https://hmis.gov.np
  email: it@hmis.gov.np

url: http://fhir.hmis.gov.np
date: 2025-08-01

copyright: >-
  Used by permission of HL7 International, all rights reserved Creative Commons License

pages:
  index.md:
    title: Home
  smart-index.md:
    title: SMART Guidelines
  profiles.md:
    title: Extensions and Profiles
  codesystems.md:
    title: Code Systems
  valuesets.md:
    title: Value Sets
  indicators.md:
    title: Indicators
  identifiers.md:
    title: Identifier Systems
  external_terminologies.md:
    title: External Code Systems
  health-journey.md:
    title: Health Journey
  security.md:
    title: Security and Privacy  
  gov_concepts.md:
    title: Governance
    archimate-diagram.md:
      title: ArchiMate Diagram
  examples.md:
    title: Examples

  downloads.md:
    title: Downloads
    copyrights.md:
      title: Copyrights

  health-journey-mnch.md:
  health-journey-immunization.md:
  health-journey-opd.md:

menu:
  Home: index.html
  SMART Guidelines: smart-index.html
  Extensions and Profiles : profiles.html
  Code Systems: codesystems.html
  Value Set: valuesets.html
  Indicators: indicators.html
  Identifier Systems: identifiers.html
  External Code Systems: external_terminologies.html
  Health Journey: health-journey.html
  Examples: examples.html
  Security and Privacy: security.html
  Authoring:
    Governance : gov_concepts.html
    ArchiMate Diagram : archimate-diagram.html
  Support:
    Downloads: downloads.html
    Copyrights: copyrights.html
  Artifacts: artifacts.html

contact:
  - name: RC Poudel
    telecom:
      - system: email
        value: rcpoudel@amakomaya.com
      - system: email
        value: rmchndrapdl@gmail.com
      - system: phone
        value: "+977-9851341921"

instanceOptions:
  manualSliceOrdering: true